## **Q1. Write a Python code to implement the KNN classifier algorithm on load_iris dataset in sklearn.datasets.**

In [5]:
from sklearn.datasets import load_iris
from sklearn.model_selection import train_test_split
from sklearn.neighbors import KNeighborsClassifier
from sklearn.metrics import confusion_matrix,accuracy_score,classification_report

In [6]:
iris=load_iris()
x=iris.data
y=iris.target
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.2,random_state=42)

In [7]:
k=3
classifier=KNeighborsClassifier(n_neighbors=k,algorithm="auto")
classifier.fit(x_train,y_train)

KNeighborsClassifier(n_neighbors=3)

In [8]:
y_pred=classifier.predict(x_test)

In [9]:
print("confusion_matrix:\n",confusion_matrix(y_test,y_pred))
print("Accuracy_score:\n",accuracy_score(y_test,y_pred))
print("classification_report:\n",classification_report(y_test,y_pred))

confusion_matrix:
 [[10  0  0]
 [ 0  9  0]
 [ 0  0 11]]
Accuracy_score:
 1.0
classification_report:
               precision    recall  f1-score   support

           0       1.00      1.00      1.00        10
           1       1.00      1.00      1.00         9
           2       1.00      1.00      1.00        11

    accuracy                           1.00        30
   macro avg       1.00      1.00      1.00        30
weighted avg       1.00      1.00      1.00        30



## **Q2. Write a Python code to implement the KNN regressor algorithm on load_boston dataset in sklearn.datasets.**

# **load_boston` has been removed from scikit-learn since version 1.2**

In [10]:
from sklearn import load_datasets
from sklearn.model_selection import train_test_split
from sklearn.neighbors import KNeighborsRegressor
from sklearn.metrics import r2_score,mean_squared_error

ImportError: cannot import name 'load_datasets' from 'sklearn' (C:\Users\Abhi\AppData\Roaming\Python\Python311\site-packages\sklearn\__init__.py)

In [ ]:
boston=load_boston()
x=boston.data
y=boston.target

In [ ]:
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.20,random_state=42)

In [ ]:
k=5
regressor=KNeighborsRegressor(n_neighbors=k,algorithm="auto")
regressor.fit(x_train,y_train)

In [ ]:
y_pred=regressor.predict(x_train) 

In [ ]:
mse = mean_squared_error(y_test, y_pred)
r2 = r2_score(y_test, y_pred)
print(f"Mean Squared Error: {mse}")
print(f"R-Squared (R2) score: {r2}")

## **Q3. Write a Python code snippet to find the optimal value of K for the KNN classifier algorithm using cross-validation on load_iris dataset in sklearn.datasets.**

In [12]:
from sklearn.datasets import load_iris
from sklearn.model_selection import cross_val_score
from sklearn.neighbors import KNeighborsClassifier

In [13]:
iris=load_iris()
x=iris.data
y=iris.target

In [14]:
k_values=list(range(1,31))
cv_scores=[]

In [15]:
for k in k_values:
    classifier=KNeighborsClassifier(n_neighbors=k)
    scores=cross_val_score(classifier,x,y,cv=10,scoring="accuracy")
    cv_scores.append(scores.mean())
optimal_k = k_values[cv_scores.index(max(cv_scores))]

In [16]:
print(f"Optimal K value: {optimal_k}")

Optimal K value: 13


## **Q4. Implement the KNN regressor algorithm with feature scaling on load_boston dataset in sklearn.datasets.**

# **load_boston` has been removed from scikit-learn since version 1.2**

In [17]:
import numpy as np
from sklearn.datasets import load_boston
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.neighbors import KNeighborsRegressor
from sklearn.metrics import mean_squared_error

ImportError: 
`load_boston` has been removed from scikit-learn since version 1.2.

The Boston housing prices dataset has an ethical problem: as
investigated in [1], the authors of this dataset engineered a
non-invertible variable "B" assuming that racial self-segregation had a
positive impact on house prices [2]. Furthermore the goal of the
research that led to the creation of this dataset was to study the
impact of air quality but it did not give adequate demonstration of the
validity of this assumption.

The scikit-learn maintainers therefore strongly discourage the use of
this dataset unless the purpose of the code is to study and educate
about ethical issues in data science and machine learning.

In this special case, you can fetch the dataset from the original
source::

    import pandas as pd
    import numpy as np

    data_url = "http://lib.stat.cmu.edu/datasets/boston"
    raw_df = pd.read_csv(data_url, sep="\s+", skiprows=22, header=None)
    data = np.hstack([raw_df.values[::2, :], raw_df.values[1::2, :2]])
    target = raw_df.values[1::2, 2]

Alternative datasets include the California housing dataset and the
Ames housing dataset. You can load the datasets as follows::

    from sklearn.datasets import fetch_california_housing
    housing = fetch_california_housing()

for the California housing dataset and::

    from sklearn.datasets import fetch_openml
    housing = fetch_openml(name="house_prices", as_frame=True)

for the Ames housing dataset.

[1] M Carlisle.
"Racist data destruction?"
<https://medium.com/@docintangible/racist-data-destruction-113e3eff54a8>

[2] Harrison Jr, David, and Daniel L. Rubinfeld.
"Hedonic housing prices and the demand for clean air."
Journal of environmental economics and management 5.1 (1978): 81-102.
<https://www.researchgate.net/publication/4974606_Hedonic_housing_prices_and_the_demand_for_clean_air>


In [ ]:
boston = load_boston()
X = boston.data
y = boston.target

In [ ]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

In [ ]:
scaler = StandardScaler()
X_train_scaled = scaler.fit_transform(X_train)
X_test_scaled = scaler.transform(X_test)

In [ ]:
k = 5  
knn_regressor = KNeighborsRegressor(n_neighbors=k)
knn_regressor.fit(X_train_scaled, y_train)

In [ ]:
y_pred = knn_regressor.predict(X_test_scaled)

In [ ]:
mse = mean_squared_error(y_test, y_pred)
print(f"Mean Squared Error (MSE): {mse}")

## **Q5. Write a Python code snippet to implement the KNN classifier algorithm with weighted voting on load_iris dataset in sklearn.datasets.**

In [18]:
from sklearn.datasets import load_iris
from sklearn.model_selection import train_test_split
from sklearn.neighbors import KNeighborsClassifier
from sklearn.metrics import accuracy_score

In [19]:
iris=load_iris()
x=iris.data
y=iris.target

In [20]:
x_train,x_test,y_train,y_test=train_test_split(x,y,random_state=42)

In [21]:
k=3
classifier=KNeighborsClassifier(n_neighbors=k,algorithm="auto",weights="distance")
classifier.fit(x_train,y_train)

KNeighborsClassifier(n_neighbors=3, weights='distance')

In [22]:
y_pred=classifier.predict(x_test)

In [23]:
accuracy=accuracy_score(y_test,y_pred)
print(f"Accuracy is: {accuracy}")

Accuracy is: 1.0


## **Q6. Implement a function to standardise the features before applying KNN classifier.**

In [24]:
import numpy as np

In [25]:
def standardize_features(x):
    mean=np.mean(x,axis=0)
    std=np.std(x,axis=0)
    std = np.where(std == 0, 1e-8, std)
    X_standardized = (x-mean) / std
    return X_standardized

In [26]:
X_train = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
X_train_standardized=standardize_features(X_train)
X_train_standardized

array([[-1.22474487, -1.22474487, -1.22474487],
       [ 0.        ,  0.        ,  0.        ],
       [ 1.22474487,  1.22474487,  1.22474487]])

## **Q7. Write a Python function to calculate the euclidean distance between two points.**

In [27]:
import math

In [28]:
def euclidean_distance(x1,y1,x2,y2):
    distance =math.sqrt((x2 - x1)**2 + (y2 - y1)**2)
    return distance

In [29]:
x1, y1 = 1.0, 2.0
x2, y2 = 4.0, 6.0

In [30]:
distance=euclidean_distance(x1,y1,x2,y2)
print(f"The Euclidean distance is: {distance}")

The Euclidean distance is: 5.0


## **Q8. Write a Python function to calculate the manhattan distance between two points.**

In [31]:
def manhattan_distance(x1,y1,x2,y2):
    distance = abs(x2-x1) + abs(y2-y1)
    return distance

In [32]:
x1, y1 = 1.0, 2.0
x2, y2 = 4.0, 6.0

In [33]:
distance=manhattan_distance(x1,y1,x2,y2)
print(f"The manhattan Distance is: {distance}")

The manhattan Distance is: 7.0
